services:
  - type: api
    name: steel-browser
    env: docker
    dockerfilePath: ./api/Dockerfile
    healthCheckPath: /v1/health
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: cache
      mountPath: /app/.cache
      sizeGB: 1
